### PR TITLE
Update codemirror and lezer

### PR DESCRIPTION
**Pull request by PhilippRaab**

### CODE REVIEW

**Comment by marijnh** [comment]
Looks like you added the build output to the repository.

**Comment by PhilippRaab** [comment]
> Looks like you added the build output to the repository.

The build output is for the demo page: https://lezer-parser.github.io/json/

**Comment by marijnh** [comment]
What I mean is that it shouldn't be checked into the repository.

**Comment by PhilippRaab** [comment]
It's already in the repo: https://github.com/lezer-parser/json/tree/master/docs
It will break the demo page when it is removed or am I missing something?

**Comment by marijnh** [comment]
Ah, sorry, github's diff showed this with only green dots, leading me to assume it was newly added.

I do think keeping build output in the repository is a bad idea, but I'll let @satchmorun decide how to merge this.

**Comment by PhilippRaab** [comment]
I agree, I will remove the build output. When @satchmorun decides to keep the build in the repo, he can add it later again.

**Comment by satchmorun** [comment]
> I do think keeping build output in the repository is a bad idea, but I'll let @satchmorun decide how to merge this.

> I agree, I will remove the build output. When @satchmorun decides to keep the build in the repo, he can add it later again.

My thinking at the time was that the `docs` directory output was a useful thing to be able to click around to see how the thing actually worked.

I'm assuming that eventually something like that will be possible on the CodeMirror docs site, which would render this (and the associated github pages site) redundant.

And the real use of it is for development anyway, so I'm happy to remove the build output and the github pages site. (NOTE: [It seems to be possible to actually use a build step to build a pages site](https://github.com/marketplace/actions/deploy-to-github-pages), but feels like more effort than it's worth at the moment).

All that's to say: this is good with me 👍. Thanks for the PR!

**Pull request merged**
