### PR TITLE
Use esm package with mocha

### PR DESCRIPTION
**Pull request by PhilippRaab**

### CODE REVIEW

**Comment by satchmorun** [comment]
Now that the other 2 PRs are merged, do you mind squashing this down? Seems that this PR can now just be the one commit "Use esm package with mocha".

**Comment by marijnh** [comment]
What does this fix? With recent Mocha versions ES module tests run fine without loading esm

**Comment by PhilippRaab** [comment]
I get following error when not using esm:

image

**Comment by marijnh** [comment]
With Mocha 8? Which node version are you running?

**Comment by PhilippRaab** [comment]
It's working now. I had to update node to version > 12.11 (see: https://github.com/mochajs/mocha/pull/4038).

**Pull request closed without merging**
